### ISSUE TITLE
shaft-coupling.stl issue

### ISSUE THREAD

**Issue by RTLflat** [bqlabs/ciclop#19]
tried downloading shaft-coupling.stl several times and and cura won't open. slic3r starts to load then crashes. uploading to netfabb gives "could not load mesh (invalid stl file)". i've printed every other part with no issues downloading files on the same computer to the same directory.

**Comment by RTLflat** [comment]
actually i just tried downloading from thingiverse and cura loaded this "same" file with no problem. only github file is problematic

**Comment by Jesus89** [comment]
OK. Thanks for the report!
