### ISSUE TITLE
Clear EEPROM

### ISSUE THREAD

**Issue by Bantum-Works** [bqlabs/ciclop#23]
Found an error / setup bug that may have caught out a few in the Horus setup : 

• Don't click on 'Clear EEPROM' or it will erase the boot loader on the Arduino board ... ! 

http://diwo.bq.com/wp-content/uploads/2015/07/preferencias-mac-177x330.png

( Not unless you want to reprogram it deliberately )

• If you do accidently erase it, here is a handy tip on how to reload it : 

https://learn.sparkfun.com/tutorials/installing-an-arduino-bootloader 

Cheers, Bantum ...

**Comment by Jesus89** [comment]
Hi, Thanks for the report! Please, for future issues go to https://github.com/bqlabs/horus.

Now 'Clear EEPROM' option adds only '-D' to 'avrdude'. This command is used to disable erasing the chip before programming. Probably playing with and without -D options can cause boot loader issues, but I can't reproduce it.

The main issue is that this option is not related to the EEPROM. I have fixed that doing always '-D -U' and erasing the EEPROM with an dedicated .hex file: https://github.com/bqlabs/horus/commit/bca692152ae0b6120983b73fb26b545079c17f6a.

Regards.
