### ISSUE TITLE
Lasers Not Working

### ISSUE THREAD

**Issue by Dbutler431** [bqlabs/ciclop#37]
I have constructed the Ciclop 3D Scanner, but the lasers are not working.
The camera works and the turntable operates during Auto Check, but I get an error message saying that the lasers have not been detected. Could anybody tell me if there is a way of switching on the lasers?

**Comment by leccybill** [comment]
Hi lasers should come on during the wizard calibration  but look in the advanced calibration you can switch left, right or both on.

**Comment by Dbutler431** [comment]
Thanks for the response. The lasers were not coming on during the wizard calibration, but they are working now having accessed them through the advanced calibration as suggested.
